import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { AdvantageSection } from "../components/layout/AdvantageSection/AdvantageSection";
import { Header } from "../components/layout/TopSection/Header";
import { TopSection } from "../components/layout/TopSection/TopSection";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Quibly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <TopSection />
      <AdvantageSection />
    </>
  );
};

export default Home;
